on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n kdpoc -g terraform --location "Southeast Asia" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n kdpoc --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n kdpoc --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n kdpoc --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: kdpoc.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t kdpoc.azurecr.io/azure-vote:${{ github.sha }} --label dockerfile-path=azure-vote/Dockerfile
        docker push kdpoc.azurecr.io/azure-vote:${{ github.sha }}
         
    - name: Set AKS context
      id: set-context
      uses: azure/aks-set-context@v3
      with:
        resource-group: 'terraform' 
        cluster-name: 'kdpoc'
          
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: kdpoc.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: myaksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: |
          azure-vote-all-in-one-redis.yaml
        images: |
          kdpoc.azurecr.io/azure-vote:${{ github.sha }}
        imagepullsecrets: |
          myaksclusterdockerauth   
